name = "TerminalBase"
uuid = "0e6ac781-a4f6-46c1-b458-cd01e5135a7a"
authors = ["Ben Lauwens <ben.lauwens@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
